name: UiPath CI/CD Sample

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: windows-latest   # UiPath CLI works best on Windows runners

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install UiPath CLI via NuGet
        shell: powershell
        run: |
          Install-PackageProvider -Name NuGet -Force
          Install-Module -Name UiPath.CLI -Force -Scope CurrentUser
          uipcli --version



